// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Encryptor is an autogenerated mock type for the Encryptor type
type Encryptor struct {
	mock.Mock
}

// Decrypt provides a mock function with given fields: ciphertext, salt, encPass
func (_m *Encryptor) Decrypt(ciphertext string, salt string, encPass string) (string, error) {
	ret := _m.Called(ciphertext, salt, encPass)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return rf(ciphertext, salt, encPass)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(ciphertext, salt, encPass)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(ciphertext, salt, encPass)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Encrypt provides a mock function with given fields: plaintext, salt, encPass
func (_m *Encryptor) Encrypt(plaintext string, salt string, encPass string) (string, error) {
	ret := _m.Called(plaintext, salt, encPass)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return rf(plaintext, salt, encPass)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(plaintext, salt, encPass)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(plaintext, salt, encPass)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateSalt provides a mock function with given fields: length, hasNumbers, hasSymbols
func (_m *Encryptor) GenerateSalt(length int, hasNumbers bool, hasSymbols bool) string {
	ret := _m.Called(length, hasNumbers, hasSymbols)

	var r0 string
	if rf, ok := ret.Get(0).(func(int, bool, bool) string); ok {
		r0 = rf(length, hasNumbers, hasSymbols)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewEncryptor creates a new instance of Encryptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEncryptor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Encryptor {
	mock := &Encryptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
