// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UserReaderInterface is an autogenerated mock type for the UserReaderInterface type
type UserReaderInterface struct {
	mock.Mock
}

// NewUserReaderInterface creates a new instance of UserReaderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserReaderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserReaderInterface {
	mock := &UserReaderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
