// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "github.com/Pedrommb91/go-auth/internal/api/models"
	mock "github.com/stretchr/testify/mock"
)

// UserRepositoryInterface is an autogenerated mock type for the UserRepositoryInterface type
type UserRepositoryInterface struct {
	mock.Mock
}

// AddUser provides a mock function with given fields: user
func (_m *UserRepositoryInterface) AddUser(user models.Users) (int64, error) {
	ret := _m.Called(user)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Users) (int64, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(models.Users) int64); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(models.Users) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepositoryInterface creates a new instance of UserRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryInterface {
	mock := &UserRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
